version: "3"

services:
  django:
    container_name: django
    build:
      context: ./django
    stdin_open: true
    tty: true
    working_dir: /src
    ports:
      - "8000:8000"
    volumes:
      - ./django:/src
      - run_vol:/var/run
      - cache_vol:/var/cache
      - tmp_vol:/tmp
    env_file:
      - .env.dev
    command: >
      sh -c "sh migrations.sh && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    networks:
      - backend

  keycloak:
    build: docker/keycloak
    env_file:
      - ./.env.dev
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: on-failure
    command: ['start']
    networks:
      - backend

volumes:
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfsd
  tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
    
networks:
  backend:
    driver: bridge